USE [master]
GO

/****** Object:  Database [CancerReporting]    Script Date: 08/09/2020 10:22:02 ******/
CREATE DATABASE [CancerReporting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CancerReporting', FILENAME = N'C:\CancerReporting.mdf' , SIZE = 10485760KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'CancerReporting_log', FILENAME = N'C:\CancerReporting_log.ldf' , SIZE = 10485760KB , MAXSIZE = 2048GB , FILEGROWTH = 524288KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CancerReporting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CancerReporting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CancerReporting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CancerReporting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CancerReporting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CancerReporting] SET ARITHABORT OFF 
GO

ALTER DATABASE [CancerReporting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CancerReporting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CancerReporting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CancerReporting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CancerReporting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CancerReporting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CancerReporting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CancerReporting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CancerReporting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CancerReporting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CancerReporting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CancerReporting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CancerReporting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CancerReporting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CancerReporting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CancerReporting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CancerReporting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CancerReporting] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CancerReporting] SET  MULTI_USER 
GO

ALTER DATABASE [CancerReporting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CancerReporting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CancerReporting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CancerReporting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CancerReporting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CancerReporting] SET QUERY_STORE = OFF
GO

USE [CancerReporting]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CancerReporting] SET  READ_WRITE 
GO

