CREATE TABLE [LocalConfig].[SCR_PTL_StatisticsDimensionGroups]
(
[StatisticsDimensionGroupId] [int] NOT NULL IDENTITY(1, 1),
[DeathStatus] [int] NULL,
[PctCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[CcgCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[CancerSite] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerSiteBS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerSubSiteCode] [int] NULL,
[ReferralCancerSiteCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteBS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerTypeCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PriorityTypeCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[SourceReferralCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[ReferralMethodCode] [int] NULL,
[TumourStatusCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusCodeCwt] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[InappropriateRef] [int] NULL,
[TransferReason] [int] NULL,
[TransferTumourSiteCode] [int] NULL,
[FastDiagCancerSiteID] [int] NULL,
[FastDiagCancerSiteOverrideID] [int] NULL,
[FastDiagCancerSiteCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagEndReasonID] [int] NULL,
[FastDiagDelayReasonID] [int] NULL,
[FastDiagExclReasonID] [int] NULL,
[FastDiagOrgID] [int] NULL,
[FastDiagCommMethodID] [int] NULL,
[FastDiagOtherCommMethod] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FastDiagInformingCareProfID] [int] NULL,
[FastDiagOtherCareProf] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FDPlannedInterval] [bit] NULL,
[AgeAtDiagnosis] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisSubCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgIdDiagnosis] [int] NULL,
[AgeAtReferral] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgIdUpgrade] [int] NULL,
[OrgIdFirstSeen] [int] NULL,
[FirstAppointmentTypeCode] [int] NULL,
[FirstAppointmentOffered] [int] NULL,
[ReasonNoAppointmentCode] [int] NULL,
[FirstSeenAdjTime] [int] NULL,
[FirstSeenAdjReasonCode] [int] NULL,
[FirstSeenDelayReasonCode] [int] NULL,
[DTTAdjTime] [int] NULL,
[DTTAdjReasonCode] [int] NULL,
[IsBCC] [int] NULL,
[IsCwtCancerDiagnosis] [int] NULL,
[UnderCancerCareFlag] [int] NULL,
[DeftTreatmentEventCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[DeftTreatmentCode] [char] (2) COLLATE Latin1_General_CI_AS NULL,
[DeftTreatmentSettingCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DeftDTTAdjTime] [int] NULL,
[DeftDTTAdjReasonCode] [int] NULL,
[DeftOrgIdDecisionTreat] [int] NULL,
[DeftOrgIdTreatment] [int] NULL,
[DeftDefinitiveTreatment] [int] NULL,
[DeftChemoRT] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[TxModModalitySubCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[TxModRadioSurgery] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[cwtFlag2WW] [int] NULL,
[cwtFlag28] [int] NULL,
[cwtFlag31] [int] NULL,
[cwtFlag62] [int] NULL,
[cwtType62] [int] NULL,
[AdjTime2WW] [int] NULL,
[AdjTime28] [int] NULL,
[AdjTime31] [int] NULL,
[AdjTime62] [int] NULL,
[DaysTo62DayBreach] [int] NULL,
[Waitingtime2WW] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[Waitingtime28] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[Waitingtime31] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[Waitingtime62] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DaysSinceLastTracked] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[Weighting] [numeric] (2, 1) NULL,
[DaysToNextBreach] [int] NULL,
[NextBreachTarget] [varchar] (17) COLLATE Latin1_General_CI_AS NULL,
[Priority2WW] [int] NULL,
[Priority28] [int] NULL,
[Priority31] [int] NULL,
[Priority62] [int] NULL,
[NextActionDesc] [varchar] (75) COLLATE Latin1_General_CI_AS NULL,
[NextActionSpecificDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DaysToNextAction] [int] NULL,
[OwnerDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Escalated] [int] NULL,
[CWTStatusCode2WW] [int] NULL,
[CWTStatusCode28] [int] NULL,
[CWTStatusCode31] [int] NULL,
[CWTStatusCode62] [int] NULL
) ON [PRIMARY]
GO
