CREATE TABLE [SCR_Reporting_History].[SCR_LastPTL_Record]
(
[InLastRefresh] [bit] NOT NULL CONSTRAINT [DF__SCR_LastP__InLas__68487DD7] DEFAULT ((1)),
[PtlSnapshotId] [int] NOT NULL,
[CWT_ID] [varchar] (255) NOT NULL CONSTRAINT [DF__SCR_LastP__CWT_I__693CA210] DEFAULT (''),
[CARE_ID] [int] NOT NULL,
[PatientPathwayID] [varchar] (20) NULL,
[PatientPathwayIdIssuer] [varchar] (3) NULL,
[PATIENT_ID] [int] NULL CONSTRAINT [DF__SCR_LastP__PATIE__6A30C649] DEFAULT ((0)),
[MainRefActionId] [int] NULL,
[DiagnosisActionId] [int] NULL,
[DemographicsActionId] [int] NULL,
[Forename] [varchar] (50) NULL,
[Surname] [varchar] (60) NULL,
[DateBirth] [date] NULL,
[HospitalNumber] [varchar] (20) NULL,
[NHSNumber] [varchar] (10) NULL,
[NHSNumberStatusCode] [varchar] (3) NULL,
[NstsStatus] [int] NULL,
[IsTemporaryNHSNumber] [int] NULL,
[DeathStatus] [int] NULL,
[DateDeath] [date] NULL,
[PctCode] [varchar] (5) NULL,
[PctDesc] [varchar] (100) NULL,
[CcgCode] [varchar] (3) NULL,
[CcgDesc] [varchar] (100) NULL,
[CancerSite] [varchar] (50) NULL,
[CancerSiteBS] [varchar] (50) NULL,
[CancerSubSiteCode] [int] NULL,
[CancerSubSiteDesc] [varchar] (25) NULL,
[ReferralCancerSiteCode] [varchar] (50) NULL,
[ReferralCancerSiteDesc] [varchar] (50) NULL,
[ReferralCancerSiteBS] [varchar] (50) NULL,
[CancerTypeCode] [varchar] (2) NULL,
[CancerTypeDesc] [varchar] (100) NULL,
[PriorityTypeCode] [varchar] (2) NULL,
[PriorityTypeDesc] [varchar] (13) NULL,
[SourceReferralCode] [varchar] (2) NULL,
[SourceReferralDesc] [varchar] (100) NULL,
[ReferralMethodCode] [int] NULL,
[DecisionToReferDate] [smalldatetime] NULL,
[TumourStatusCode] [varchar] (50) NULL,
[TumourStatusDesc] [varchar] (50) NULL,
[PatientStatusCode] [varchar] (2) NULL,
[PatientStatusDesc] [varchar] (100) NULL,
[PatientStatusCodeCwt] [varchar] (2) NULL,
[PatientStatusDescCwt] [varchar] (100) NULL,
[ConsultantCode] [varchar] (8) NULL,
[ConsultantName] [varchar] (255) NULL,
[InappropriateRef] [int] NULL,
[TransferReason] [int] NULL,
[TransferNewRefDate] [smalldatetime] NULL,
[TransferTumourSiteCode] [int] NULL,
[TransferTumourSiteDesc] [varchar] (100) NULL,
[TransferActionedDate] [smalldatetime] NULL,
[TransferSourceCareId] [int] NULL,
[TransferOrigSourceCareId] [int] NULL,
[FastDiagInformedDate] [smalldatetime] NULL,
[FastDiagExclDate] [datetime] NULL,
[FastDiagCancerSiteID] [int] NULL,
[FastDiagCancerSiteOverrideID] [int] NULL,
[FastDiagCancerSiteCode] [varchar] (2) NULL,
[FastDiagCancerSiteDesc] [varchar] (50) NULL,
[FastDiagEndReasonID] [int] NULL,
[FastDiagEndReasonCode] [varchar] (2) NULL,
[FastDiagEndReasonDesc] [varchar] (25) NULL,
[FastDiagDelayReasonID] [int] NULL,
[FastDiagDelayReasonCode] [varchar] (2) NULL,
[FastDiagDelayReasonDesc] [varchar] (160) NULL,
[FastDiagDelayReasonComments] [varchar] (max) NULL,
[FastDiagExclReasonID] [int] NULL,
[FastDiagExclReasonCode] [varchar] (2) NULL,
[FastDiagExclReasonDesc] [varchar] (80) NULL,
[FastDiagOrgID] [int] NULL,
[FastDiagOrgCode] [varchar] (5) NULL,
[FastDiagOrgDesc] [varchar] (100) NULL,
[FastDiagCommMethodID] [int] NULL,
[FastDiagCommMethodCode] [varchar] (2) NULL,
[FastDiagCommMethodDesc] [varchar] (30) NULL,
[FastDiagOtherCommMethod] [varchar] (50) NULL,
[FastDiagInformingCareProfID] [int] NULL,
[FastDiagInformingCareProfCode] [varchar] (3) NULL,
[FastDiagInformingCareProfDesc] [varchar] (70) NULL,
[FastDiagOtherCareProf] [varchar] (50) NULL,
[DateDiagnosis] [smalldatetime] NULL,
[AgeAtDiagnosis] [int] NULL,
[DiagnosisCode] [varchar] (5) NULL,
[DiagnosisSubCode] [varchar] (5) NULL,
[DiagnosisDesc] [varchar] (150) NULL,
[DiagnosisSubDesc] [varchar] (150) NULL,
[OrgIdDiagnosis] [int] NULL,
[OrgCodeDiagnosis] [varchar] (5) NULL,
[OrgDescDiagnosis] [varchar] (250) NULL,
[SnomedCT_ID] [int] NULL,
[SnomedCT_MCode] [varchar] (10) NULL,
[SnomedCT_ConceptID] [bigint] NULL,
[SnomedCT_Desc] [varchar] (100) NULL,
[Histology] [varchar] (10) NULL,
[DateReceipt] [smalldatetime] NULL,
[AgeAtReferral] [int] NULL,
[AppointmentCancelledDate] [smalldatetime] NULL,
[DateConsultantUpgrade] [smalldatetime] NULL,
[DateFirstSeen] [smalldatetime] NULL,
[OrgIdUpgrade] [int] NULL,
[OrgCodeUpgrade] [varchar] (5) NULL,
[OrgDescUpgrade] [varchar] (250) NULL,
[OrgIdFirstSeen] [int] NULL,
[OrgCodeFirstSeen] [varchar] (5) NULL,
[OrgDescFirstSeen] [varchar] (250) NULL,
[FirstAppointmentTypeCode] [int] NULL,
[FirstAppointmentTypeDesc] [varchar] (255) NULL,
[FirstAppointmentOffered] [int] NULL,
[ReasonNoAppointmentCode] [int] NULL,
[ReasonNoAppointmentDesc] [varchar] (255) NULL,
[FirstSeenAdjTime] [int] NULL,
[FirstSeenAdjReasonCode] [int] NULL,
[FirstSeenAdjReasonDesc] [varchar] (150) NULL,
[FirstSeenDelayReasonCode] [int] NULL,
[FirstSeenDelayReasonDesc] [varchar] (255) NULL,
[FirstSeenDelayReasonComment] [varchar] (max) NULL,
[DTTAdjTime] [int] NULL,
[DTTAdjReasonCode] [int] NULL,
[DTTAdjReasonDesc] [varchar] (150) NULL,
[IsBCC] [int] NULL,
[IsCwtCancerDiagnosis] [int] NULL,
[UnderCancerCareFlag] [int] NULL,
[RefreshMaxActionDate] [datetime] NULL,
[ReferralReportDate] [datetime] NULL,
[CWTInsertIx] [int] NOT NULL,
[OriginalCWTInsertIx] [int] NULL,
[Tx_ID] [varchar] (255) NOT NULL CONSTRAINT [DF__SCR_LastP__Tx_ID__6B24EA82] DEFAULT (''),
[TREATMENT_ID] [int] NULL,
[TREAT_ID] [int] NULL,
[CHEMO_ID] [int] NULL,
[TELE_ID] [int] NULL,
[PALL_ID] [int] NULL,
[BRACHY_ID] [int] NULL,
[OTHER_ID] [int] NULL,
[SURGERY_ID] [int] NULL,
[MONITOR_ID] [int] NULL,
[ChemoActionId] [int] NULL,
[TeleActionId] [int] NULL,
[PallActionId] [int] NULL,
[BrachyActionId] [int] NULL,
[OtherActionId] [int] NULL,
[SurgeryActionId] [int] NULL,
[MonitorActionId] [int] NULL,
[DeftTreatmentEventCode] [varchar] (2) NULL,
[DeftTreatmentEventDesc] [varchar] (100) NULL,
[DeftTreatmentCode] [char] (2) NULL,
[DeftTreatmentDesc] [varchar] (100) NULL,
[DeftTreatmentSettingCode] [varchar] (50) NULL,
[DeftTreatmentSettingDesc] [varchar] (100) NULL,
[DeftDateDecisionTreat] [smalldatetime] NULL,
[DeftDateTreatment] [smalldatetime] NULL,
[DeftDTTAdjTime] [int] NULL,
[DeftDTTAdjReasonCode] [int] NULL,
[DeftDTTAdjReasonDesc] [varchar] (150) NULL,
[DeftOrgIdDecisionTreat] [int] NULL,
[DeftOrgCodeDecisionTreat] [varchar] (5) NULL,
[DeftOrgDescDecisionTreat] [varchar] (250) NULL,
[DeftOrgIdTreatment] [int] NULL,
[DeftOrgCodeTreatment] [varchar] (5) NULL,
[DeftOrgDescTreatment] [varchar] (250) NULL,
[DeftDefinitiveTreatment] [int] NULL,
[DeftChemoRT] [varchar] (2) NULL,
[TxModTreatmentEventCode] [varchar] (2) NULL,
[TxModTreatmentEventDesc] [varchar] (100) NULL,
[TxModTreatmentCode] [char] (2) NULL,
[TxModTreatmentDesc] [varchar] (100) NULL,
[TxModTreatmentSettingCode] [varchar] (50) NULL,
[TxModTreatmentSettingDesc] [varchar] (100) NULL,
[TxModDateDecisionTreat] [smalldatetime] NULL,
[TxModDateTreatment] [smalldatetime] NULL,
[TxModOrgIdDecisionTreat] [int] NULL,
[TxModOrgCodeDecisionTreat] [varchar] (5) NULL,
[TxModOrgDescDecisionTreat] [varchar] (250) NULL,
[TxModOrgIdTreatment] [int] NULL,
[TxModOrgCodeTreatment] [varchar] (5) NULL,
[TxModOrgDescTreatment] [varchar] (250) NULL,
[TxModDefinitiveTreatment] [int] NULL,
[TxModChemoRadio] [varchar] (2) NULL,
[TxModChemoRT] [varchar] (2) NULL,
[TxModModalitySubCode] [varchar] (2) NULL,
[TxModRadioSurgery] [varchar] (2) NULL,
[ChemRtLinkTreatmentEventCode] [varchar] (2) NULL,
[ChemRtLinkTreatmentEventDesc] [varchar] (100) NULL,
[ChemRtLinkTreatmentCode] [char] (2) NULL,
[ChemRtLinkTreatmentDesc] [varchar] (100) NULL,
[ChemRtLinkTreatmentSettingCode] [varchar] (50) NULL,
[ChemRtLinkTreatmentSettingDesc] [varchar] (100) NULL,
[ChemRtLinkDateDecisionTreat] [smalldatetime] NULL,
[ChemRtLinkDateTreatment] [smalldatetime] NULL,
[ChemRtLinkOrgIdDecisionTreat] [int] NULL,
[ChemRtLinkOrgCodeDecisionTreat] [varchar] (5) NULL,
[ChemRtLinkOrgDescDecisionTreat] [varchar] (250) NULL,
[ChemRtLinkOrgIdTreatment] [int] NULL,
[ChemRtLinkOrgCodeTreatment] [varchar] (5) NULL,
[ChemRtLinkOrgDescTreatment] [varchar] (250) NULL,
[ChemRtLinkDefinitiveTreatment] [int] NULL,
[ChemRtLinkChemoRadio] [varchar] (2) NULL,
[ChemRtLinkModalitySubCode] [varchar] (2) NULL,
[ChemRtLinkRadioSurgery] [varchar] (2) NULL,
[cwtFlag2WW] [int] NULL,
[cwtFlag28] [int] NULL,
[cwtFlag31] [int] NULL,
[cwtFlag62] [int] NULL,
[cwtType2WW] [int] NULL,
[cwtType28] [int] NULL,
[cwtType31] [int] NULL,
[cwtType62] [int] NULL,
[cwtReason2WW] [int] NULL,
[cwtReason28] [int] NULL,
[cwtReason31] [int] NULL,
[cwtReason62] [int] NULL,
[HasTxMod] [int] NULL CONSTRAINT [DF__SCR_LastP__HasTx__6C190EBB] DEFAULT ((0)),
[HasChemRtLink] [int] NULL CONSTRAINT [DF__SCR_LastP__HasCh__6D0D32F4] DEFAULT ((0)),
[ClockStartDate2WW] [smalldatetime] NULL,
[ClockStartDate28] [smalldatetime] NULL,
[ClockStartDate31] [smalldatetime] NULL,
[ClockStartDate62] [smalldatetime] NULL,
[AdjTime2WW] [int] NULL,
[AdjTime28] [int] NULL,
[AdjTime31] [int] NULL,
[AdjTime62] [int] NULL,
[TargetDate2WW] [smalldatetime] NULL,
[TargetDate28] [smalldatetime] NULL,
[TargetDate31] [smalldatetime] NULL,
[TargetDate62] [smalldatetime] NULL,
[DaysTo2WWBreach] [int] NULL,
[DaysTo28DayBreach] [int] NULL,
[DaysTo31DayBreach] [int] NULL,
[DaysTo62DayBreach] [int] NULL,
[ClockStopDate2WW] [smalldatetime] NULL,
[ClockStopDate28] [smalldatetime] NULL,
[ClockStopDate31] [smalldatetime] NULL,
[ClockStopDate62] [smalldatetime] NULL,
[Waitingtime2WW] [int] NULL,
[Waitingtime28] [int] NULL,
[Waitingtime31] [int] NULL,
[Waitingtime62] [int] NULL,
[Breach2WW] [int] NULL,
[Breach28] [int] NULL,
[Breach31] [int] NULL,
[Breach62] [int] NULL,
[DaysTo62DayBreachNoDTT] [int] NULL,
[Treated7Days] [int] NULL,
[Treated7Days62Days] [int] NULL,
[FutureAchieve62Days] [int] NULL,
[FutureFail62Days] [int] NULL,
[ActualWaitDTTTreatment] [int] NULL,
[DTTTreated7Days] [int] NULL,
[Treated7Days31Days] [int] NULL,
[Treated7DaysBreach31Days] [int] NULL,
[FutureAchieve31Days] [int] NULL,
[FutureFail31Days] [int] NULL,
[FutureDTT] [int] NULL,
[NoDTTDate] [int] NULL,
[LastCommentUser] [varchar] (50) NULL,
[LastCommentDate] [datetime] NULL,
[CwtReportDate] [datetime] NULL,
[Pathway] [varchar] (255) NULL,
[TrackingNotes] [varchar] (max) NULL,
[DateLastTracked] [datetime] NULL,
[CommentUser] [varchar] (50) NULL,
[DaysSinceLastTracked] [int] NULL,
[Weighting] [numeric] (2, 1) NULL,
[DaysToNextBreach] [int] NULL,
[NextBreachTarget] [varchar] (17) NULL,
[NextBreachDate] [smalldatetime] NULL,
[DominantColourValue] [varchar] (255) NULL,
[ColourValue2WW] [varchar] (255) NULL,
[ColourValue28Day] [varchar] (255) NULL,
[ColourValue31Day] [varchar] (255) NULL,
[ColourValue62Day] [varchar] (255) NULL,
[DominantColourDesc] [varchar] (255) NULL,
[ColourDesc2WW] [varchar] (255) NULL,
[ColourDesc28Day] [varchar] (255) NULL,
[ColourDesc31Day] [varchar] (255) NULL,
[ColourDesc62Day] [varchar] (255) NULL,
[DominantPriority] [int] NULL,
[Priority2WW] [int] NULL,
[Priority28] [int] NULL,
[Priority31] [int] NULL,
[Priority62] [int] NULL,
[PathwayUpdateEventID] [int] NULL,
[NextActionDesc] [varchar] (75) NULL,
[NextActionSpecificDesc] [varchar] (50) NULL,
[NextActionTargetDate] [date] NULL,
[DaysToNextAction] [int] NULL,
[OwnerDesc] [varchar] (50) NULL,
[AdditionalDetails] [varchar] (55) NULL,
[Escalated] [int] NULL,
[ReportingPathwayLength] [int] NULL,
[DominantCWTStatusCode] [int] NULL,
[DominantCWTStatusDesc] [varchar] (255) NULL,
[CWTStatusCode2WW] [int] NULL,
[CWTStatusDesc2WW] [varchar] (255) NULL,
[CWTStatusCode28] [int] NULL,
[CWTStatusDesc28] [varchar] (255) NULL,
[CWTStatusCode31] [int] NULL,
[CWTStatusDesc31] [varchar] (255) NULL,
[CWTStatusCode62] [int] NULL,
[CWTStatusDesc62] [varchar] (255) NULL,
[SSRS_PTLFlag62] [int] NULL,
[FDPlannedInterval] [bit] NULL
) ON [PRIMARY]
GO
ALTER TABLE [SCR_Reporting_History].[SCR_LastPTL_Record] ADD CONSTRAINT [PK_SCR_LastPTL_Record] PRIMARY KEY CLUSTERED  ([CWT_ID] DESC) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [Ix_CARE_ID] ON [SCR_Reporting_History].[SCR_LastPTL_Record] ([CARE_ID] DESC) ON [PRIMARY]
GO
