CREATE TABLE [SCR_Warehouse].[SCR_Referrals_work]
(
[CARE_ID] [int] NOT NULL,
[PatientPathwayID] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[PatientPathwayIdIssuer] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[PATIENT_ID] [int] NULL CONSTRAINT [DF__SCR_Refer__PATIE__03BB8E22] DEFAULT ((0)),
[MainRefActionId] [int] NULL,
[DiagnosisActionId] [int] NULL,
[DemographicsActionId] [int] NULL,
[Forename] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[Surname] [varchar] (60) COLLATE Latin1_General_CI_AS NULL,
[DateBirth] [date] NULL,
[HospitalNumber] [varchar] (20) COLLATE Latin1_General_CI_AS NULL,
[NHSNumber] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[NHSNumberStatusCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[NstsStatus] [int] NULL,
[IsTemporaryNHSNumber] [int] NULL,
[DeathStatus] [int] NULL,
[DateDeath] [date] NULL,
[PctCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[PctDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CcgCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[CcgDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[CancerSite] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerSiteBS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerSubSiteCode] [int] NULL,
[CancerSubSiteDesc] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[ReferralCancerSiteBS] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[CancerTypeCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[CancerTypeDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PriorityTypeCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PriorityTypeDesc] [varchar] (13) COLLATE Latin1_General_CI_AS NULL,
[SourceReferralCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[SourceReferralDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ReferralMethodCode] [int] NULL,
[DecisionToReferDate] [smalldatetime] NULL,
[TumourStatusCode] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[TumourStatusDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusCodeCwt] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[PatientStatusDescCwt] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[ConsultantCode] [varchar] (8) COLLATE Latin1_General_CI_AS NULL,
[ConsultantName] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[InappropriateRef] [int] NULL,
[TransferReason] [int] NULL,
[TransferNewRefDate] [smalldatetime] NULL,
[TransferTumourSiteCode] [int] NULL,
[TransferTumourSiteDesc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[TransferActionedDate] [smalldatetime] NULL,
[TransferSourceCareId] [int] NULL,
[TransferOrigSourceCareId] [int] NULL,
[FastDiagInformedDate] [smalldatetime] NULL,
[FastDiagExclDate] [datetime] NULL,
[FastDiagCancerSiteID] [int] NULL,
[FastDiagCancerSiteOverrideID] [int] NULL,
[FastDiagCancerSiteCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagCancerSiteDesc] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FastDiagEndReasonID] [int] NULL,
[FastDiagEndReasonCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagEndReasonDesc] [varchar] (25) COLLATE Latin1_General_CI_AS NULL,
[FastDiagDelayReasonID] [int] NULL,
[FastDiagDelayReasonCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagDelayReasonDesc] [varchar] (160) COLLATE Latin1_General_CI_AS NULL,
[FastDiagDelayReasonComments] [varchar] (max) COLLATE Latin1_General_CI_AS NULL,
[FastDiagExclReasonID] [int] NULL,
[FastDiagExclReasonCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagExclReasonDesc] [varchar] (80) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOrgID] [int] NULL,
[FastDiagOrgCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOrgDesc] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
[FastDiagCommMethodID] [int] NULL,
[FastDiagCommMethodCode] [varchar] (2) COLLATE Latin1_General_CI_AS NULL,
[FastDiagCommMethodDesc] [varchar] (30) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOtherCommMethod] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[FastDiagInformingCareProfID] [int] NULL,
[FastDiagInformingCareProfCode] [varchar] (3) COLLATE Latin1_General_CI_AS NULL,
[FastDiagInformingCareProfDesc] [varchar] (70) COLLATE Latin1_General_CI_AS NULL,
[FastDiagOtherCareProf] [varchar] (50) COLLATE Latin1_General_CI_AS NULL,
[DateDiagnosis] [smalldatetime] NULL,
[AgeAtDiagnosis] [int] NULL,
[DiagnosisCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisSubCode] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[DiagnosisSubDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[OrgIdDiagnosis] [int] NULL,
[OrgCodeDiagnosis] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescDiagnosis] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
[SnomedCT_ID] [int] NULL,
[SnomedCT_MCode] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[SnomedCT_ConceptID] [bigint] NULL,
[SnomedCT_Desc] [varchar] (100) COLLATE Latin1_General_CI_AS NULL,
[Histology] [varchar] (10) COLLATE Latin1_General_CI_AS NULL,
[DateReceipt] [smalldatetime] NULL,
[AgeAtReferral] [int] NULL,
[AppointmentCancelledDate] [smalldatetime] NULL,
[DateConsultantUpgrade] [smalldatetime] NULL,
[DateFirstSeen] [smalldatetime] NULL,
[OrgIdUpgrade] [int] NULL,
[OrgCodeUpgrade] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescUpgrade] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
[OrgIdFirstSeen] [int] NULL,
[OrgCodeFirstSeen] [varchar] (5) COLLATE Latin1_General_CI_AS NULL,
[OrgDescFirstSeen] [varchar] (250) COLLATE Latin1_General_CI_AS NULL,
[FirstAppointmentTypeCode] [int] NULL,
[FirstAppointmentTypeDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstAppointmentOffered] [int] NULL,
[ReasonNoAppointmentCode] [int] NULL,
[ReasonNoAppointmentDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstSeenAdjTime] [int] NULL,
[FirstSeenAdjReasonCode] [int] NULL,
[FirstSeenAdjReasonDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[FirstSeenDelayReasonCode] [int] NULL,
[FirstSeenDelayReasonDesc] [varchar] (255) COLLATE Latin1_General_CI_AS NULL,
[FirstSeenDelayReasonComment] [varchar] (max) COLLATE Latin1_General_CI_AS NULL,
[DTTAdjTime] [int] NULL,
[DTTAdjReasonCode] [int] NULL,
[DTTAdjReasonDesc] [varchar] (150) COLLATE Latin1_General_CI_AS NULL,
[IsBCC] [int] NULL,
[IsCwtCancerDiagnosis] [int] NULL,
[UnderCancerCareFlag] [int] NULL,
[RefreshMaxActionDate] [datetime] NULL,
[ReportDate] [datetime] NULL,
[DateLastTracked] [datetime] NULL,
[DaysSinceLastTracked] [int] NULL
) ON [PRIMARY]
GO
