CREATE TABLE [SCR_Reporting_History].[CheckCurrentLoadedSnapshot]
(
[CWT_ID] [varchar] (255) NOT NULL,
[PatientPathwayID] [varchar] (max) NULL,
[CancerTypeCode] [varchar] (max) NULL,
[Waitingtime2WW] [real] NULL,
[Waitingtime28] [real] NULL,
[Waitingtime31] [real] NULL,
[Waitingtime62] [real] NULL,
[LastCommentUser] [varchar] (max) NULL,
[LastCommentDate] [datetime2] NULL,
[DateLastTracked] [datetime2] NULL,
[DaysSinceLastTracked] [real] NULL,
[DaysToNextBreach] [real] NULL,
[NextBreachTarget] [varchar] (max) NULL,
[PriorityTypeCode] [varchar] (max) NULL,
[NextBreachDate] [datetime2] NULL,
[NextActionDesc] [varchar] (max) NULL,
[NextActionSpecificDesc] [varchar] (max) NULL,
[NextActionTargetDate] [datetime2] NULL,
[OwnerDesc] [varchar] (max) NULL,
[Escalated] [real] NULL,
[DominantCWTStatusCode] [real] NULL,
[CWTStatusCode2WW] [real] NULL,
[CWTStatusCode28] [real] NULL,
[CWTStatusCode31] [real] NULL,
[SourceReferralCode] [varchar] (max) NULL,
[CWTStatusCode62] [real] NULL,
[ReferralMethodCode] [real] NULL,
[DecisionToReferDate] [datetime2] NULL,
[TumourStatusCode] [varchar] (max) NULL,
[PatientStatusCode] [varchar] (max) NULL,
[PatientStatusCodeCwt] [varchar] (max) NULL,
[ConsultantCode] [varchar] (max) NULL,
[InappropriateRef] [real] NULL,
[DateBirth] [datetime2] NULL,
[TransferReason] [real] NULL,
[TransferNewRefDate] [datetime2] NULL,
[TransferTumourSiteCode] [real] NULL,
[FastDiagInformedDate] [datetime2] NULL,
[FastDiagExclDate] [datetime2] NULL,
[FastDiagCancerSiteID] [real] NULL,
[FastDiagCancerSiteOverrideID] [real] NULL,
[FastDiagEndReasonID] [real] NULL,
[FastDiagDelayReasonID] [real] NULL,
[FastDiagExclReasonID] [real] NULL,
[DeathStatus] [real] NULL,
[FastDiagOrgID] [real] NULL,
[FastDiagCommMethodID] [real] NULL,
[FastDiagOtherCommMethod] [varchar] (max) NULL,
[FastDiagInformingCareProfID] [real] NULL,
[FastDiagOtherCareProf] [varchar] (max) NULL,
[DateDiagnosis] [datetime2] NULL,
[DiagnosisCode] [varchar] (max) NULL,
[DiagnosisSubCode] [varchar] (max) NULL,
[OrgIdDiagnosis] [real] NULL,
[SnomedCT_ID] [real] NULL,
[DateDeath] [datetime2] NULL,
[Histology] [varchar] (max) NULL,
[DateReceipt] [datetime2] NULL,
[DateConsultantUpgrade] [datetime2] NULL,
[DateFirstSeen] [datetime2] NULL,
[OrgIdUpgrade] [real] NULL,
[OrgIdFirstSeen] [real] NULL,
[FirstAppointmentTypeCode] [real] NULL,
[FirstAppointmentOffered] [real] NULL,
[ReasonNoAppointmentCode] [real] NULL,
[FirstSeenAdjTime] [real] NULL,
[CancerSite] [varchar] (max) NULL,
[FirstSeenAdjReasonCode] [real] NULL,
[FirstSeenDelayReasonCode] [real] NULL,
[DTTAdjTime] [real] NULL,
[DTTAdjReasonCode] [real] NULL,
[IsBCC] [real] NULL,
[IsCwtCancerDiagnosis] [real] NULL,
[UnderCancerCareFlag] [real] NULL,
[DeftTreatmentEventCode] [varchar] (max) NULL,
[DeftTreatmentCode] [varchar] (max) NULL,
[DeftTreatmentSettingCode] [varchar] (max) NULL,
[CancerSiteBS] [varchar] (max) NULL,
[DeftDateDecisionTreat] [datetime2] NULL,
[DeftDateTreatment] [datetime2] NULL,
[DeftDTTAdjTime] [real] NULL,
[DeftDTTAdjReasonCode] [real] NULL,
[DeftOrgIdDecisionTreat] [real] NULL,
[DeftOrgIdTreatment] [real] NULL,
[DeftDefinitiveTreatment] [real] NULL,
[DeftChemoRT] [varchar] (max) NULL,
[TxModTreatmentEventCode] [varchar] (max) NULL,
[TxModTreatmentCode] [varchar] (max) NULL,
[CancerSubSiteCode] [real] NULL,
[TxModTreatmentSettingCode] [varchar] (max) NULL,
[TxModDateDecisionTreat] [datetime2] NULL,
[TxModDateTreatment] [datetime2] NULL,
[TxModOrgIdDecisionTreat] [real] NULL,
[TxModOrgIdTreatment] [real] NULL,
[TxModDefinitiveTreatment] [real] NULL,
[TxModChemoRadio] [varchar] (max) NULL,
[TxModChemoRT] [varchar] (max) NULL,
[TxModModalitySubCode] [varchar] (max) NULL,
[TxModRadioSurgery] [varchar] (max) NULL,
[ReferralCancerSiteCode] [varchar] (max) NULL,
[ChemRtLinkTreatmentCode] [varchar] (max) NULL,
[ChemRtLinkDateTreatment] [datetime2] NULL,
[cwtFlag2WW] [real] NULL,
[cwtFlag28] [real] NULL,
[cwtFlag31] [real] NULL,
[cwtFlag62] [real] NULL,
[cwtType2WW] [real] NULL,
[cwtType28] [real] NULL,
[cwtType31] [real] NULL,
[cwtType62] [real] NULL,
[ReferralCancerSiteBS] [varchar] (max) NULL,
[cwtReason2WW] [real] NULL,
[cwtReason28] [real] NULL,
[cwtReason31] [real] NULL,
[cwtReason62] [real] NULL,
[HasTxMod] [real] NULL,
[HasChemRtLink] [real] NULL,
[AdjTime2WW] [real] NULL,
[AdjTime28] [real] NULL,
[AdjTime31] [real] NULL,
[AdjTime62] [real] NULL,
[FDPlannedInterval] [real] NULL
) ON [PRIMARY]
GO
